# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

#import pleco_target.pleco_target_pb2 as pleco__target__pb2
#from pleco_target.pleco_target_pb2 import K8sGWRequest
import pleco_target_pb2 as pleco__target__pb2

class K8sGWStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNSs = channel.unary_unary(
                '/K8sGW/GetNSs',
                request_serializer=pleco__target__pb2.K8sGWRequest.SerializeToString,
                response_deserializer=pleco__target__pb2.K8sGWResponse.FromString,
                )
        self.ApplyDeployment = channel.unary_unary(
                '/K8sGW/ApplyDeployment',
                request_serializer=pleco__target__pb2.K8sGWRequest.SerializeToString,
                response_deserializer=pleco__target__pb2.K8sGWResponse.FromString,
                )
        self.ApplyService = channel.unary_unary(
                '/K8sGW/ApplyService',
                request_serializer=pleco__target__pb2.K8sGWRequest.SerializeToString,
                response_deserializer=pleco__target__pb2.K8sGWResponse.FromString,
                )
        self.DeleteDeployment = channel.unary_unary(
                '/K8sGW/DeleteDeployment',
                request_serializer=pleco__target__pb2.K8sGWRequest.SerializeToString,
                response_deserializer=pleco__target__pb2.K8sGWResponse.FromString,
                )
        self.DeleteService = channel.unary_unary(
                '/K8sGW/DeleteService',
                request_serializer=pleco__target__pb2.K8sGWRequest.SerializeToString,
                response_deserializer=pleco__target__pb2.K8sGWResponse.FromString,
                )
        self.TestConnection = channel.unary_unary(
                '/K8sGW/TestConnection',
                request_serializer=pleco__target__pb2.K8sGWRequest.SerializeToString,
                response_deserializer=pleco__target__pb2.K8sGWResponse.FromString,
                )


class K8sGWServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNSs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_K8sGWServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNSs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNSs,
                    request_deserializer=pleco__target__pb2.K8sGWRequest.FromString,
                    response_serializer=pleco__target__pb2.K8sGWResponse.SerializeToString,
            ),
            'ApplyDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyDeployment,
                    request_deserializer=pleco__target__pb2.K8sGWRequest.FromString,
                    response_serializer=pleco__target__pb2.K8sGWResponse.SerializeToString,
            ),
            'ApplyService': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyService,
                    request_deserializer=pleco__target__pb2.K8sGWRequest.FromString,
                    response_serializer=pleco__target__pb2.K8sGWResponse.SerializeToString,
            ),
            'DeleteDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDeployment,
                    request_deserializer=pleco__target__pb2.K8sGWRequest.FromString,
                    response_serializer=pleco__target__pb2.K8sGWResponse.SerializeToString,
            ),
            'DeleteService': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteService,
                    request_deserializer=pleco__target__pb2.K8sGWRequest.FromString,
                    response_serializer=pleco__target__pb2.K8sGWResponse.SerializeToString,
            ),
            'TestConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.TestConnection,
                    request_deserializer=pleco__target__pb2.K8sGWRequest.FromString,
                    response_serializer=pleco__target__pb2.K8sGWResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'K8sGW', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class K8sGW(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNSs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/K8sGW/GetNSs',
            pleco__target__pb2.K8sGWRequest.SerializeToString,
            pleco__target__pb2.K8sGWResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ApplyDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/K8sGW/ApplyDeployment',
            pleco__target__pb2.K8sGWRequest.SerializeToString,
            pleco__target__pb2.K8sGWResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ApplyService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/K8sGW/ApplyService',
            pleco__target__pb2.K8sGWRequest.SerializeToString,
            pleco__target__pb2.K8sGWResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/K8sGW/DeleteDeployment',
            pleco__target__pb2.K8sGWRequest.SerializeToString,
            pleco__target__pb2.K8sGWResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/K8sGW/DeleteService',
            pleco__target__pb2.K8sGWRequest.SerializeToString,
            pleco__target__pb2.K8sGWResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/K8sGW/TestConnection',
            pleco__target__pb2.K8sGWRequest.SerializeToString,
            pleco__target__pb2.K8sGWResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
